try:

except:
    raise # raise same error
    pass # pass this except and resume
